version: "3"

services:
  front:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.front
    ports:
    - "3000:3000"
    volumes:
      - .:/app/
    # entrypoint: "npm run serve"
    tty: true


