FROM node:17-buster AS BUILD_IMAGE

ENV APP_PATH='/app/front'
ENV APP_USER='node'

WORKDIR $APP_PATH
RUN chown -R $APP_USER:$APP_USER $APP_PATH

RUN apt-get update
RUN apt-get -y install locales && \
	localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8 \
	LANGUAGE ja_JP:ja \
	LC_ALL ja_JP.UTF-8 \
	TZ JST-9

COPY ./front/package*.json ./
RUN npm ci

